### ISSUE TITLE
Maybe there is a better solution.

### ISSUE THREAD

**Issue by gloryknight** [masotime/json-url#13]
Hi, 
I thought that you will be interested to know that there is a better solution: LZString.compressToEncodedURIComponent : https://github.com/JobLeonard/lz-string . This is stable and battle proven compression library.
For your use case `LZString.compressToEncodedURIComponent(JSON.stringify( obj ))` will do the job. Works everywhere.
A smaller, faster and tuned version can be found in my repository:  https://github.com/gloryknight/LZstr/raw/master/LZStr2.0.1.min.js
This one is 2.7kb total, compresses at about 18 Mbytes/s and returns the result immediately. When applied to your example page the original data of 8246 is converted to 5959 bytes JSON text which is compressed to 2623 bytes URI encoded text. Even without conversion (including the spaces the result is better than in your example page).
However, I think you did a nice attempt in popularizing compression for data exchange.

**Comment by bengoh** [comment]
Thanks for the feedback. I actually do use lzstring as one of the algorithms, as mentioned in https://github.com/masotime/json-url#approach

I notice you're referencing 2.0.1 though - which perhaps solved the URI encoding still using `+`.

It's a little hard to make sense of the stats that you mention - could you give specific examples of input and output data...? It's also unclear if your adaptation uses LZW or LZMA for the statistics you mention...?

**Comment by gloryknight** [comment]
Sorry for the confusion, I have not checked your repository completely. Indeed, you do have LZString. And I was using LZW for my tests. LZMA looks better. 
PS: I have solved the `+` problem with LZString 2.0.1 version. Now it should be rfc3986 compatible.
Good luck.
