### ISSUE TITLE
Any way to include this as a flat .js file on the client side?

### ISSUE THREAD

**Issue by TheGameKnave** [masotime/json-url#2]
I'm not using node but need to encode some URIs safely. I'm having a little trouble figuring out how to flat-file this library. Any chance you could lend a hand?

**Comment by masotime** [comment]
Hey @jugglervr, currently I didn't plan to make it a universal / client-side module. It's definitely within the realm of possibility, but not really on my schedule at the moment. I'll see if I can find time to make a client side or universal version though.

**Comment by masotime** [comment]
@jugglervr It's been a long time, and you've probably moved on, but v2.2 now has a standalone bundle for this purpose. It's a little large though, have to figure out how to bring down the size of it.

**Comment by masotime** [comment]
After fiddling with Webpack 3 I was able to split the bundles further in v2.3. Main entry chunk is still surprisingly large though (56kb minified, 20kb gzipped)
