### ISSUE TITLE
Test page - include file missing

### ISSUE THREAD

**Issue by flyingzebra** [masotime/json-url#3]
If that is not too much trouble, I woud like to suggest to add pre-webpacked file json-url.js in the test directory.  As I would love to use this project for client-side integration, installing nodeJS and webpack module to generate one Javascript file would mean quite a hassle.

**Comment by masotime** [comment]
Hi @flyingzebra, thanks for the report! I've updated v2.3.4 to include the necessary files in the `dist/` folder. Let me know if you encounter any other issues.
